services:
  - type: web
    name: focustrivia
    env: php
    buildCommand: |
      composer install --no-dev
      php artisan key:generate
      php artisan migrate --force
    startCommand: php -S 0.0.0.0:10000 -t public
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:YOUR_APP_KEY_HERE
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-xxx
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: focustrivia_db
      - key: DB_USERNAME
        value: focustrivia_db_user
      - key: DB_PASSWORD
        value: your_password
